version: "3"

tasks:
  # Convenience

  install:taskfile:
    cmds:
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
  
  install:ssh:
    cmds:
      - ssh-keygen -f ~/.ssh/textflowrhyme
      - cat ~/.ssh/textflowrhyme.pub
      - echo "Add this key to DigitalOcean now and name it 'textflowrhyme'"

  install:terraform:
    cmds:
      - sudo apt update && sudo apt install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      - |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update && sudo apt install terraform

  install:ansible:
    cmds:
      - sudo apt install ansible

  terraform:apply:
    cmds:
      - |
        while true; do
            read -p "Have you uploaded 'textflowrhyme' SSH key to DigitalOcean? (yes/no) " yn
            case $yn in
                [Yy]* ) break;;
                [Nn]* ) exit 1;;
                * ) echo "Please answer yes or no.";;
            esac
        done
      - terraform apply -var-file=.tfvars
      - echo "Copy your droplet’s IP to your Ansible inventory"
    dir: ./terraform

  terraform:destroy:
    cmds:
      - terraform destroy -var-file=.tfvars
    dir: ./terraform

  ansible:install:docker:
    cmds:
      - ansible-playbook -i inventory.yml playbooks/docker.yml
    dir: ./ansible
