---
- name: Install Docker
  hosts: textflowrhyme
  remote_user: root
  become: yes

  tasks:
    - name: Update dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - git
        update_cache: yes
    
    - name: Add key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu mantic stable"
        state: present
        filename: docker
    
    - name: Install Docker
      apt:
        name: 
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: present
    
    - name: Check Docker
      ansible.builtin.service:
        name: docker
        state: started

    - name: Clone repository
      ansible.builtin.git:
        repo: https://github.com/42juododranoel/textflowrhyme-infrastructure
        dest: /root/textflowrhyme-infrastructure
