name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Reload Containers
        uses: appleboy/ssh-action@master
        with:
          host: 142.93.102.51
          username: root
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/textflowrhyme-infrastructure
            git pull origin master
            ~/bin/task docker:restart
